### ISSUE TITLE
ios permissions

### ISSUE THREAD

**Issue by pocket-care** [firescript/nativescript-contacts#10]
Hi

Could I please find out where is the code that prompts access to contacts permissions to be granted on ios? 
And how to check if this is granted.
I did a bit of googling i think for ios its CNAuthorizationStatus and requestAccessForEntityType
Could you please integrate to check if access is granted for both ios and android? Wont take you long but will take me ages.

Thanks

**Comment by alv909** [comment]
> where is the code that prompts access to contacts permissions to be granted on ios?

For iOS 10+, add this to your Info.plist file (App_Resources\iOS) and the user will be prompted as soon as your code makes a call to CNContactStore:

<key>Privacy - Contacts Usage Description</key>
<string>This application requires access to your contacts.</string>

See also: https://developer.apple.com/documentation/contacts. Hope that helps.

**Comment by jzgoda** [comment]
Docs have been updated to show how to avoid this issue.
