### ISSUE TITLE
iOS: file:///app/tns_modules/nativescript-contacts/index.js:35:40: JS ERROR ReferenceError: Can't find variable: CNContactPickerDelegate

### ISSUE THREAD

**Issue by einicher** [firescript/nativescript-contacts#12]
Had no problems with your plugin on android, but on iOS `tns run ios` crashes with:

`file:///app/tns_modules/nativescript-contacts/index.js:35:40: JS ERROR ReferenceError: Can't find variable: CNContactPickerDelegate`

**Comment by PeterStaev** [comment]
Hey @einicher ,  what version of iOS are you running the plugin? From the error seems you are trying to run the app in iOS8 or earlier. Note that the plugin uses the ContactFramework and thus works only on iOS9+.

**Comment by einicher** [comment]
ok, ios version of the test iphone is 8.3
no way to support versions prior to 9.0?
