### ISSUE TITLE
Android: Permission denial reading

### ISSUE THREAD

**Issue by einicher** [firescript/nativescript-contacts#14]
Hi,
on my android testphone - were it worked until now - i get this exception:

```
Error: java.lang.SecurityException: Permission Denial: reading
com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/display_photo/2 from pid=26745, uid=10441 requires android.PERMISSION.READ_CONTACTS or grantUriPermission()
```

Permissions are not added to AndroidManifest.xml, if i add them by hand i still get the same error.

Also tried these suggstions: http://stackoverflow.com/questions/8104776/permission-read-contacts-does-not-seem-to-work - no success

Any hints?

**Comment by einicher** [comment]
Building with AndroidStudio gave a better hint @firescript:

Warning:The file: /home/mre/PROJECTS/test/node_modules/nativescript-contacts/platforms/android/AndroidManifest.xml is depricated, you can read more about what will be the expected plugin structure here: https://www.nativescript.org/blog/migrating-n-android-plugins-from-version-1.7-to-2.0

**Comment by PeterStaev** [comment]
Hey @einicher , although CLI throws this warning, it is a false one, as it was decided to keep AndroidManifest for plugins. You can read more [here](https://github.com/NativeScript/android-runtime/issues/369#issuecomment-209367198). 

Have you installed the plugin using `tns install nativescript-contacts`? Also can you try to clean your android platforms and then building your project again:
```
tns platform clean android
tns deploy android
```

**Comment by einicher** [comment]
i did several times.
```
rm -rf node_modules platforms
tns platform add android
tns run android
```
same outcome, it shows me the contact selection dialog, but when i pick a contact i get the permission denied exception.

**Comment by einicher** [comment]
is it possible it has something to with
```
sudo npm install -g nativescript
npm install tns-core-modules@latest --save
```
i suddenly have to do this everytime i start a new project or else i get the error “app.js not found”

**Comment by sitefinitysteve** [comment]
It's this android 6?

**Comment by einicher** [comment]
@sitefinitysteve
yes, android version 6.0.1

**Comment by sitefinitysteve** [comment]
Can you try this? https://www.npmjs.com/package/nativescript-permissions

**Comment by einicher** [comment]
@sitefinitysteve “Woo Hoo, I have the power”
it works.
Very important contribution, I would have nver thought about that, I thought it asks by itself, like qr-plugin does.
thx!!

**Comment by sitefinitysteve** [comment]
I'll see what i can do, or at least document it

**Comment by koganalon** [comment]
You'll need a Runtime permission.
with or without placing the permission in your manifest, You will need to request that permission from the User on-the-fly.

if( getApplicationContext().checkSelfPermission( Manifest.permission.READ_CONTACTS ) != PackageManager.PERMISSION_GRANTED )
     ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.READ_CONTACTS}, resultValue);

only then after the approval you will be able to query the contacts phone number/name etc.

**Comment by jzgoda** [comment]
Docs have been updated to avoid this issue.

**Comment by hinalt** [comment]
I still get this error. Can you please paste an working example to explain this?
