### ISSUE TITLE
Porting to NativeScript 3.0

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [firescript/nativescript-contacts#24]
Hello there,
This useful plugin doesn't work on NativeScript 3.0. I am using `getContact()`, and it's `Promise` return doesn't seem to call its callbacks. Any interest in porting the plugin to {N} 3.0?

**Comment by pascaloo7** [comment]
Any updates on this issue? I'm having the exact same problem.

**Comment by Dragomir-Ivanov** [comment]
@pascaloo7 Can you confirm that the plugin works for iOS for you? Maybe I will can to dig deeper on this.

**Comment by firescript** [comment]
This should be fixed: https://github.com/firescript/nativescript-contacts/blob/master/index.android.js#L17

**Comment by Dragomir-Ivanov** [comment]
@firescript 
Thank you. Works like a charm!
