### ISSUE TITLE
getContactsInGroup() not taking parameters

### ISSUE THREAD

**Issue by joey0xx** [firescript/nativescript-contacts#26]
When i do;
```
var group = args.data[0]
contacts.getContactsInGroup(group)
```
I get the error:  `Supplied parameters do not match any signature of call target`. In fact, all of the other functions that are supposed to take a parameter throw that error. The function getContact(), works well.

I'm using NS 3.0 with Angular/TS.

**Comment by NitayRabi** [comment]
Duplicate of #27
