### ISSUE TITLE
Console.dump deprecated in NativeScript 3.0

### ISSUE THREAD

**Issue by ugocast** [firescript/nativescript-contacts#35]
console.dump has been deprecated from NativeScript 3.0 in favor of console.dir, you can fix this? i have the next error :

file:///app/tns_modules/nativescript-contacts/index.js:83:25: JS ERROR TypeError: console.dump is not a function. (In 'console.dump(e)', 'console.dump' is undefined)

Thanks!

**Comment by Sharique-Hasan** [comment]
@firescript Can you please look into this. I am also seeing this error.

**Comment by rolaru** [comment]
+1 here.

**Comment by firescript** [comment]
alright this is working in a fresh nativescript app running 3.2.1 - want to confirm? @Sharique-Hasan @rolaru @ugocast - pushed the update to npm

**Comment by rolaru** [comment]
@firescript, sorry for responding late. I've tested the plugin now and it seems to work fine. Thanks a lot for the fix!
