### ISSUE TITLE
Issue while doing a webpack

### ISSUE THREAD

**Issue by mayureshjadhav** [firescript/nativescript-contacts#38]
Hi,

I am having issue while doing a webpack. Following is the issue I am getting

"ERROR in ../node_modules/nativescript-contacts/index.android.js
Module not found: Error: Can't resolve './get-contacts-by-name-worker.js'"

I am using tns 3.2.1

**Comment by DivyeshSharma** [comment]
I am also facing the same issue? Can anyone please help on urgent basis?

Thanking in advance!

**Comment by lewebsimple** [comment]
Something to do with `nativescript-worker-loader` ...

**Comment by pauly815** [comment]
Keep seeing this in the logs on iOS using TNS 3.4.2

***** Fatal JavaScript exception on worker thread - worker thread has been terminated. *****

**Comment by jzgoda** [comment]
Resolved by PR #50
