### ISSUE TITLE
Not Able to Pass the Retrieved Contact to My Own API Service

### ISSUE THREAD

**Issue by san18793** [firescript/nativescript-contacts#41]
I am able to get the contact from the phone using nativescript-contacts but I am unable to pass it to my API which is in a custom function from contacts.getContact().then(function (args) {} method.

I defined a PUBLIC VARIABLE (Object or String or Array) to which I am trying to store the contact but this is not working. It is showing an error

ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'PUBLIC VARIABLE')

**Comment by jzgoda** [comment]
This doesn't sound like an issue with the plugin, and since this is over a year old without any activity, I'm closing it.
