### ISSUE TITLE
Publish 1.6.0 to npm

### ISSUE THREAD

**Issue by jzgoda** [firescript/nativescript-contacts#68]
@firescript, can you please publish the latest version to npm?
Thanks!

**Comment by firescript** [comment]
bumped version: https://www.npmjs.com/package/nativescript-contacts

**Comment by jzgoda** [comment]
Sorry about reopening this, would you mind pushing another update to NPM for 1.6.2?

**Comment by jzgoda** [comment]
Thank you!
