### ISSUE TITLE
Question: Android Cursor

### ISSUE THREAD

**Issue by bthurlow** [firescript/nativescript-contacts#8]
Since we are passing back native objects, won't passing back the cursor cause a memory leak since we are not closing it?

Should we be thinking of some other way to pass back a native android object other than the cursor that way we can ensure it is closed?

Input appreciated!

**Comment by sitefinitysteve** [comment]
Oooh, in the promise, is this where you mean?

https://github.com/firescript/nativescript-contacts/blob/master/index.android.js#L38

**Comment by bthurlow** [comment]
Yes, that's the place.  I did the same thing on the fetches I created, but then I got to thinking about the possible leak and decided to ask the question.

**Comment by PeterStaev** [comment]
May be we should not return it in the promises? I cannot think of any reason for the user to need the cursor or the native iOS object.

**Comment by sitefinitysteve** [comment]
No, you are 1000% right :)  I don't think we should be doing this at all.  Everything is now exposed much more cleanly in pure JS.

Honestly we just did that in rev 1 because we were missing so much, and I was very new to Cursors! 

Good catch I would say...we can kill them

**Comment by bthurlow** [comment]
Sounds good, I'll start rewriting the changes that I've been making to kill the native objects in the returns.

Thanks guys!

**Comment by sitefinitysteve** [comment]
I'll be in OSX later today and yank them all out
