### ISSUE TITLE
[iOS 13+] The plugin shouldn't include "note" for iOS by default

### ISSUE THREAD

**Issue by fpaaske** [firescript/nativescript-contacts#89]
Now the methods `getContactById` and `getContactsInGroup` will always fail unless you add the key `com.apple.developer.contacts.notes` to the app.entitlements as described [here](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_contacts_notes)

In addition you'll have to apply to Apple to request permission to use this entitlement.

I believe most apps needing access to contacts, won't need access to the contact notes by default.
Please consider removing "note" from `keysToFetch` and let callers of the method provide the list instead.

**Comment by firescript** [comment]
Alright - can you submit a PR. Alway are you interested in becoming a collaborator? This repo needs help to stay maintained.

**Comment by fpaaske** [comment]
I'd love to help, but I don't know how to work with plugins and would need some good introductions to even get started.
