### ISSUE TITLE
Problem with nativescript 8

### ISSUE THREAD

**Issue by Bidou44** [firescript/nativescript-contacts#95]
I tried to upgrade our app to nativescript 8 but the nativescript-contact plugin has some issue. I already opened a ticket here https://github.com/NativeScript/NativeScript/issues/9345 as I was not sure where the problem was.

**Comment by Bidou44** [comment]
@firescript I think that an update of the lib to replace short imports is needed to be compatible with nativescript 8 (see the response to my question in the nativescript repo)

**Comment by firescript** [comment]
Hey @Bidou44 do you want to PR a fix for this issue?

**Comment by VepretskiyD** [comment]
@firescript , I'm facing the same issue on NS8 Android
